### ISSUE TITLE
IMU outliers drift?

### ISSUE THREAD

**Issue by YangSiri** [hku-mars/FAST_LIO#153]
Hi, DALAOMEN

I'm testing fast_lio with VLP16 and mti-300. However, it seems there are some outliers in the imu data. But i'm not so sure as the beginner. What would cause the tremendous drift in the pic? It happens at specific time without lack of imu data. 

scene1 at 64.7s
![fast_lio_still_drift](https://user-images.githubusercontent.com/33154113/165435429-47d24b36-6e21-4f03-a047-f1f07fb46b59.png)

scene2 at 16.4s
![fast_lio_gostraight_drift](https://user-images.githubusercontent.com/33154113/165435477-f7d5f89c-14b0-4fcb-a4de-5163782a125a.png)

Looking forward to your help~

**Comment by kxch928925819** [comment]
你这貌似是imu标定的有问题 和我一个毛病 我在考虑的是： 第一、 是不是数据输出频率太低 目前出错是100hz 想改为200hz 。
第二，lidar imu标定的参数误差较大 考虑再次标定一下。 我也被标定结果困扰的不行，没有找到最恰当的解决方法！




------------------ Original ------------------
From: ***@***.*** ***@***.***&gt;
Date: Wed,Apr 27,2022 11:43 AM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] IMU outliers drift? (Issue #153)





 
Hi, DALAOMEN
 
I'm testing fast_lio with VLP16 and mti-300. However, it seems there are some outliers in the imu data. But i'm not so sure as the beginner. What would cause the tremendous drift in the pic? It happens at specific time without lack of imu data.
 
scene1 at 64.7s
 
 
scene2 at 16.4s
 
 
Looking forward to your help~

**Comment by YangSiri** [comment]
Thanks, @kxch928925819 

First, my IMU data is 200hz though with some of missings at full seconds.
Second, since the system runs for a while with a good mapping result, i dont think it is the extrinsic that causes this drift.

**Comment by kxch928925819** [comment]
谢谢！找了一台win xp版本的电脑，使用官网程序，设置为200hz，问题解决了！




------------------ Original ------------------
From: YangSiri ***@***.***&gt;
Date: Sun,May 1,2022 9:16 PM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Weiguo Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] IMU outliers drift? (Issue #153)





 
Thanks, @kxch928925819
 
First, my IMU data is 200hz though with some of missings at full seconds.
 Second, since the system runs for a while with a good mapping result, i dont think it is the extrinsic that causes this drift.

**Comment by kxch928925819** [comment]
还是标定结果的问题，我的水平有点低，标定做了很多次，还是不能在lio-sam和fast-lio取得好成果，如果你有好经营，希望能分享，中午又去标定了一下，有好结果我会告诉你！ 共勉！




------------------ Original ------------------
From: YangSiri ***@***.***&gt;
Date: Sun,May 1,2022 9:16 PM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Weiguo Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] IMU outliers drift? (Issue #153)





 
Thanks, @kxch928925819
 
First, my IMU data is 200hz though with some of missings at full seconds.
 Second, since the system runs for a while with a good mapping result, i dont think it is the extrinsic that causes this drift.

**Comment by YangSiri** [comment]
Thannk you, @kxch928925819 

I have confirmed that this phenomenon is caused by large values in IMU raw data. So I wonder how to deal with it in fast_lio. 
BTW, the extrinsic of my system is measured by hand.

**Comment by kxch928925819** [comment]
src/config/*.yaml






------------------ Original ------------------
From: YangSiri ***@***.***&gt;
Date: Thu,May 5,2022 4:57 PM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Weiguo Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] IMU outliers drift? (Issue #153)





 
Thannk you, @kxch928925819
 
I have confirmed that this phenomenon is caused by large values in IMU raw data. So I wonder how to deal with it in fast_lio.
 BTW, the extrinsic of my system is measured by hand.

**Comment by pjs9115916** [comment]
> 还是标定结果的问题，我的水平有点低，标定做了很多次，还是不能在lio-sam和fast-lio取得好成果，如果你有好经营，希望能分享，中午又去标定了一下，有好结果我会告诉你！ 共勉！
> […](#)
> ------------------ Original ------------------ From: YangSiri ***@***.***&gt; Date: Sun,May 1,2022 9:16 PM To: hku-mars/FAST_LIO ***@***.***&gt; Cc: Weiguo Zhao ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [hku-mars/FAST_LIO] IMU outliers drift? (Issue #153) Thanks, @kxch928925819 First, my IMU data is 200hz though with some of missings at full seconds. Second, since the system runs for a while with a good mapping result, i dont think it is the extrinsic that causes this drift. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

get the extrinsic from measurement by cad is better then align
