### ISSUE TITLE
宏LASER_POINT_COV在ESEKF更新过程中有什么作用?

### ISSUE THREAD

**Issue by liang0724s** [hku-mars/FAST_LIO#162]
#define LASER_POINT_COV     (0.001)
kf.update_iterated_dyn_share_modified(**LASER_POINT_COV**, solve_H_time);

**Comment by WFram** [comment]
`LASER_POINT_COV` is a covariance for LiDAR measurements and participates in calculating Kalman gain process which is essential to update the state vector.

**Comment by liang0724s** [comment]
> `LASER_POINT_COV` is a covariance for LiDAR measurements and participates in calculating Kalman gain process which is essential to update the state vector.

Thanks, and how to get this value? is it from the LiDAR  user manual?

**Comment by WFram** [comment]
There are many factors affecting measurement process, so in general this information can't be provided by only one value. Ideally, you need to take into account each individual measurement. And Livox Custom Messages actually provide this information in tag field (see https://www.livoxtech.com/showcase/livox-tag), but I would say, it's about confidence in general, rather than specific values. Even so, you can neglect this and approximate by one number and apparently it will not affect accuracy too much. But will increase performance significantly, since you don't need to calculate high-dimensional matrices and use only a scalar value.
