### ISSUE TITLE
发布的odometry的坐标系

### ISSUE THREAD

**Issue by PengKunPROO** [hku-mars/FAST_LIO#218]
请问一下代码中odomAftMapped这个里面存储的四元数和位置向量都是关于世界坐标系（即第一帧IMU的body坐标系）吗？

**Comment by WFram** [comment]
Yes. Because to create the odometry message, the pose it taken directly from the current EKF state. And the EKF state stores a transformation from IMU frame to the World frame (IMU -> World), as stated in the paper (III-C). Also, it's clear from the functions that transform points to the world frame.
