### ISSUE TITLE
Support for L515

### ISSUE THREAD

**Issue by satyajitghana** [hku-mars/FAST_LIO#39]
Hey, do you guys have any pointers on how to integrate L515 with FAST_LIO

I've seen https://github.com/hku-mars/FAST_LIO/blob/c8aea0dd95e4f78203b79329dd59ccdd687c1bd7/src/preprocess.cpp#L49-L66

And also seen the specific handers for each lidar, but i am not able to figure out how to write a `l515_handler`, in specific i can't figure out the processing function to convert the PCL data from L515 into `PointCloudXYZI` format.

**Comment by XW-HKU** [comment]
integrate l515 is a little bit complicate.

First, if you can get the pointcloud2 topic same as velodyne,then you do not need to modify preprocess.cpp.

Besides, since the l515's a lidar frame is sampled at a same time, not like velodyne that sampled as a sequence of time, So you need to close the backward propagation in imu_processing.cpp

In the end, you should set the filter_size_surf and filter_size_map to smaller ones.

**Comment by gongyue666** [comment]
@Leonard-Yao can it work with L515? I am trying to do the same thing .

**Comment by XW-HKU** [comment]
> @Leonard-Yao can it work with L515? I am trying to do the same thing .

the support for L515 will soon be released

**Comment by Leonard-Yao** [comment]
> > @Leonard-Yao can it work with L515? I am trying to do the same thing .
> 
> the support for L515 will soon be released

@XW-HKU cheers and looking forward to. Please let me know if it`s released, thanks advance.

**Comment by Leonard-Yao** [comment]
@gongyue666 It can work, but not stable.

**Comment by Taeyoung96** [comment]
@Leonard-Yao   
How could you set the launch file when you use realsense l515?  
Do you have any tips?
