### ISSUE TITLE
Livox AVIA fast lio slam? 

### ISSUE THREAD

**Issue by antun008** [hku-mars/FAST_LIO#89]
https://github.com/gisbi-kim/FAST_LIO_SLAM/issues/19

Does anyone knows, what to change in launch or c++ files, in order that SC_PGO will work for livox Avia?

Thanks a lot,
Antun

**Comment by kxch928925819** [comment]
我试过livox horizon 在sc-pgo ，1、地下车库采集数据，在fast-lio运行采集rosbag，sc-pgo一起运行，发现部分区域的点云出现没有匹配上的重影，而fadt-lio没有问题。2、地下车库及地面建筑物一并采集中，sc-pgo出现点云混乱，无法形成有效成果，而fast-lio仅仅在一个位置出现重影。
avia买不到，刚定了mid-70，还有velodyne-16，准备试试前者提高Fov的效果，试试后者的36*270旋转效果！ 一家之言，不足以采信！





------------------ Original ------------------
From: antun008 ***@***.***&gt;
Date: Tue,Oct 19,2021 8:51 PM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] Livox AVIA fast lio slam?  (Issue #89)





 
gisbi-kim#19
 
Does anyone knows, what to change in launch or c++ files, in order that SC_PGO will work for livox Avia?
 
Thanks a lot,
 Antun
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by antun008** [comment]
Please, can you write in English?

**Comment by h-rover** [comment]
Did anybody succeed with the Livox Avia or Mid-70?
